### ISSUE TITLE
Is this available on AMO?

### ISSUE THREAD

**Issue by Gitoffthelawn** [igorlogius/get-youtube-feeds#1]
Thanks for all the great extensions!

Is this one on AMO any more?  I'm not seeing it there any longer.

**Comment by igorlogius** [comment]
> Thanks for all the great extensions!

No problem. Happy to hear others find my silly addons use/helpful. 

> Is this one on AMO any more? I'm not seeing it there any longer.

I havend completely removed it from AMO ... it is currently only hidden

It opted to stop development of it in favour of https://addons.mozilla.org/firefox/addon/list-feeds
which is a generalized (site independed) feed detection addon. 

The source ist keep here mostly for posterity, but i guess i should somehow mark the repo as inactive/archived.

**Comment by igorlogius** [comment]
Found the settings to archive the repo. Thanks for the heads up.
